# Generated by Django 3.1.6 on 2021-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_movies',
            field=models.ManyToManyField(to='movies.Movie', verbose_name='Favourite movies'),
        ),
    ]
